using System.Collections;
using System.Globalization;
using Avalonia.Data.Converters;
using FolhasDaMichelly.Application.Documents;
using FolhasDaMichelly.Contracts.Clients;
using FolhasDaMichelly.Contracts.Dispatch;
using FolhasDaMichelly.Contracts.Documents;

namespace FolhasDaMichelly.Desktop.Models;

public sealed class FriendlyTextConverter : IValueConverter
{
    public object Convert(object? value, Type targetType, object? parameter, CultureInfo culture) =>
        ToFriendlyText(value);

    public object ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture) =>
        throw new NotSupportedException();

    public static string ToFriendlyText(object? value) => value switch
    {
        null => string.Empty,
        PersonTypeModel.Individual => "Pessoa física",
        PersonTypeModel.LegalEntity => "Empresa",
        ClientPartnerRoleModel.ManagingPartner => "Sócio-administrador",
        ClientPartnerRoleModel.Partner => "Sócio",
        ClientPartnerRoleModel.Administrator => "Administrador",
        ClientPartnerRoleModel.LegalRepresentative => "Representante legal",
        ClientPartnerRoleModel.Other => "Outro vínculo",
        ClientIdentifierTypeModel.Cnpj => "CNPJ",
        ClientIdentifierTypeModel.CnpjRoot => "Raiz do CNPJ",
        ClientIdentifierTypeModel.Cpf => "CPF",
        ClientIdentifierTypeModel.InternalCode => "Código do sistema contábil",
        ClientIdentifierTypeModel.LegalNameAlias => "Outro nome conhecido",
        ClientIdentifierTypeModel.Other => "Outro identificador",
        DeliveryRoleModel.To => "Destinatário principal",
        DeliveryRoleModel.Cc => "Receber em cópia",
        DeliveryRoleModel.InternalCopy => "Cópia interna do escritório",
        DispatchOperationMode.Test => "Teste seguro",
        DispatchOperationMode.Draft => "Salvar como rascunho",
        DispatchOperationMode.Send => "Enviar aos destinatários",
        FakeDeliveryScenario.Success => "Funcionamento normal",
        FakeDeliveryScenario.TransientFailure => "Falha temporária",
        FakeDeliveryScenario.PermanentFailure => "Falha permanente",
        FakeDeliveryScenario.Timeout => "Tempo esgotado",
        FakeDeliveryScenario.Ambiguous => "Resultado incerto",
        ReviewDocumentState.Blocked => "Precisa de correção",
        ReviewDocumentState.Ready => "Pronto para agrupar",
        ReviewDocumentState.Grouped => "Pronto para revisar",
        ReviewDocumentState.Approved => "Aprovado",
        ReviewDocumentState.Duplicate => "Documento repetido",
        ReviewGroupState.Building => "Organizando documentos",
        ReviewGroupState.Blocked => "Precisa de correção",
        ReviewGroupState.ReadyForReview => "Pronto para aprovar",
        ReviewGroupState.Approved => "Aprovado",
        DispatchItemState.Blocked => "Precisa de correção",
        DispatchItemState.ReadyForApproval => "Pronto para conferir",
        DispatchItemState.Approved => "Aprovado",
        DispatchItemState.DraftCreating => "Criando rascunho",
        DispatchItemState.DraftCreated => "Rascunho criado",
        DispatchItemState.Sending => "Enviando",
        DispatchItemState.AcceptedByProvider => "Recebido pelo serviço de e-mail",
        DispatchItemState.Failed => "Não concluído",
        DispatchItemState.Ambiguous => "Resultado incerto — conferir",
        DispatchItemState.Reconciled => "Situação conferida",
        DispatchItemState.Completed => "Concluído",
        DispatchItemState.Cancelled => "Cancelado",
        ValidationSeverity.Info => "Informação",
        ValidationSeverity.Warning => "Atenção",
        ValidationSeverity.Error => "Corrigir antes de continuar",
        ValidationSeverity.Blocker => "Ação obrigatória",
        RecognitionConfidence.Low => "Confiança baixa",
        RecognitionConfidence.Medium => "Confiança média",
        RecognitionConfidence.High => "Confiança alta",
        RecognizedDocumentType documentType => DocumentPresentation.ToPortugueseLabel(documentType),
        SemanticFieldRole.EmployerTaxId => "CNPJ do empregador",
        SemanticFieldRole.ClientTaxId => "Documento do cliente",
        SemanticFieldRole.EstablishmentTaxId => "CNPJ da filial",
        SemanticFieldRole.EmployeeCpf => "CPF do empregado",
        SemanticFieldRole.UnionTaxId => "CNPJ do sindicato",
        SemanticFieldRole.DocumentIssuerTaxId => "Documento do emissor",
        SemanticFieldRole.PartnerCpf => "CPF do sócio",
        SemanticFieldRole.EmployerName => "Nome do empregador",
        SemanticFieldRole.ClientName => "Nome do cliente",
        SemanticFieldRole.EmployeeName => "Nome do empregado",
        SemanticFieldRole.UnionName => "Nome do sindicato",
        SemanticFieldRole.InternalCode => "Código interno",
        SemanticFieldRole.Competence => "Competência",
        SemanticFieldRole.AssessmentPeriod => "Período de apuração",
        SemanticFieldRole.DueDate => "Vencimento",
        SemanticFieldRole.TotalAmount => "Valor total",
        SemanticFieldRole.VacationPeriod => "Período de férias",
        SemanticFieldRole.EventDate => "Data do evento",
        ClientResolutionMethod.None => "Cliente ainda não identificado",
        ClientResolutionMethod.ExactClientTaxId => "Documento principal do cliente",
        ClientResolutionMethod.ExactEstablishmentTaxId => "CNPJ de uma filial cadastrada",
        ClientResolutionMethod.UniqueCnpjRootAndName => "Raiz do CNPJ e nome da empresa",
        ClientResolutionMethod.ExactIndividualTaxId => "CPF do cliente",
        ClientResolutionMethod.ExactInternalCode => "Código interno",
        ClientResolutionMethod.ExactLegalName => "Nome completo",
        ClientResolutionMethod.ExactAlias => "Outro nome cadastrado",
        ClientResolutionMethod.FuzzySuggestion => "Sugestão por nome — exige conferência",
        ClientResolutionMethod.ManualOverride => "Cliente confirmado manualmente",
        IEnumerable<DispatchRecipientSnapshot> recipients =>
            string.Join(", ", recipients.Select(recipient => recipient.Email)),
        IEnumerable<string> strings => string.Join(", ", strings),
        string text => TranslateAction(text),
        IEnumerable values => string.Join(", ", values.Cast<object>().Select(ToFriendlyText)),
        _ => value.ToString() ?? string.Empty,
    };

    private static string TranslateAction(string value) => value switch
    {
        "unauthenticated-operator" => "Operador local",
        "unauthenticated-connected-operator" => "Operador conectado",
        "local-operator" => "Operador local",
        "created" => "Cadastro criado",
        "updated" => "Cadastro atualizado",
        "deactivated" => "Cadastro inativado",
        "reactivated" => "Cadastro reativado",
        "archived" => "Excluído da lista — auditoria preservada",
        "imported" => "Cadastro restaurado",
        "document.imported" => "Documento importado",
        "workspace.revalidated" => "Documentos analisados novamente",
        "document.period_corrected" => "Competência corrigida",
        "document.period_restored" => "Competência reconhecida restaurada",
        "document.removed_from_review" => "Documento retirado da revisão",
        "document.client_overridden" => "Cliente confirmado manualmente",
        "document.validated" => "Documento conferido",
        "document.grouped" => "Documento incluído em um conjunto",
        "group.split" => "Conjunto separado",
        "group.merged" => "Conjuntos unidos",
        "group.empty_removed" => "Conjunto vazio retirado",
        "group.approved" => "Conjunto liberado para mensagem",
        "group.approval_invalidated" => "Aprovação revogada após alteração",
        "groups.selection_approved" => "Conjuntos selecionados liberados",
        "groups.client_approved" => "Conjuntos prontos do cliente liberados",
        "groups.bulk_approved" => "Conjuntos prontos do mês liberados",
        "document_imported" => "Documento importado",
        "workspace_revalidated" => "Documentos conferidos novamente",
        "group_approved" => "Conjunto liberado para mensagem",
        "client_overridden" => "Cliente corrigido manualmente",
        "group_split" => "Conjunto separado",
        "groups_merged" => "Conjuntos unidos",
        "dispatch_prepared" => "Mensagem preparada",
        "dispatch_composed" => "Mensagem preparada",
        "dispatch_approval_invalidated" => "Aprovação da mensagem revogada após alteração",
        "dispatch_approved" => "Mensagem aprovada",
        "dispatch_bulk_approved" => "Mensagens prontas do mês aprovadas",
        "provider_call_started" => "Operação de e-mail iniciada",
        "provider_call_completed" => "Operação no serviço de e-mail concluída",
        "provider_reconciled" => "Situação consultada sem repetir a operação",
        "dispatch_completed" => "Operação de e-mail concluída",
        "dispatch_reconciled" => "Resultado conferido",
        "reports_exported" => "Relatórios exportados",
        "email_provider_connected" => "Conta de e-mail conectada",
        "email_provider_disconnected" => "Conta de e-mail desconectada",
        "connected" => "Conectado",
        "disconnected" => "Desconectado",
        "completed" => "Concluído",
        "pending" => "Em andamento",
        "failed" => "Não concluído",
        "ReadyForApproval" => "Pronto para aprovação",
        "Approved" => "Aprovado",
        "DraftCreated" => "Rascunho criado",
        "AcceptedByProvider" => "Aceito pelo serviço de e-mail",
        "Completed" => "Concluído",
        "Failed" => "Não concluído",
        "Ambiguous" => "Resultado incerto",
        "Reconciled" => "Situação conferida",
        "Cancelled" => "Cancelado",
        "Snapshot de conteúdo e agrupamento; não autoriza envio de e-mail." =>
            "Conteúdo e organização registrados; isto ainda não envia e-mail.",
        _ => value.Replace('_', ' '),
    };
}
