<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenIddict.Client.SystemIntegration" />
    <PackageReference Include="OpenIddict.Client.SystemNetHttp" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../FolhasDaMichelly.Application/FolhasDaMichelly.Application.csproj" />
    <ProjectReference Include="../FolhasDaMichelly.Contracts/FolhasDaMichelly.Contracts.csproj" />
    <ProjectReference Include="../FolhasDaMichelly.Domain/FolhasDaMichelly.Domain.csproj" />
  </ItemGroup>
</Project>
