package br.com.contadoresassociados.folhas.contracts.documents;

public enum ClientResolutionMethod { NONE, EXACT_CLIENT_TAX_ID, EXACT_ESTABLISHMENT_TAX_ID, UNIQUE_CNPJ_ROOT_AND_NAME, EXACT_INDIVIDUAL_TAX_ID, EXACT_INTERNAL_CODE, EXACT_LEGAL_NAME, EXACT_ALIAS, FUZZY_SUGGESTION, MANUAL_OVERRIDE }
