package br.com.contadoresassociados.folhas.contracts.documents;

public enum SemanticFieldRole { UNKNOWN, EMPLOYER_TAX_ID, CLIENT_TAX_ID, ESTABLISHMENT_TAX_ID, EMPLOYEE_CPF, UNION_TAX_ID, DOCUMENT_ISSUER_TAX_ID, PARTNER_CPF, EMPLOYER_NAME, CLIENT_NAME, EMPLOYEE_NAME, UNION_NAME, INTERNAL_CODE, COMPETENCE, ASSESSMENT_PERIOD, DUE_DATE, TOTAL_AMOUNT, VACATION_PERIOD, EVENT_DATE }
