-- Baseline idêntico ao esquema criado pelas 5 migrations EF Core da versão .NET
-- (InitialCentralPhase2 .. AddPartnerOptionalEmail). Bancos existentes NÃO executam este
-- arquivo: o Flyway faz baseline na versão 1 depois de conferir o __EFMigrationsHistory.

CREATE TABLE audit_events (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DeviceId" uuid NULL,
    "EntityType" character varying(80) NOT NULL,
    "EntityId" character varying(80) NOT NULL,
    "Action" character varying(80) NOT NULL,
    "Category" character varying(80) NOT NULL,
    "Severity" character varying(32) NOT NULL,
    "RedactedDataJson" jsonb NOT NULL,
    "TimestampUtc" timestamp with time zone NOT NULL,
    "CorrelationId" uuid NOT NULL,
    CONSTRAINT "PK_audit_events" PRIMARY KEY ("Id")
);

CREATE TABLE device_sessions (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DeviceName" character varying(160) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "LastSeenAtUtc" timestamp with time zone NOT NULL,
    "RevokedAtUtc" timestamp with time zone NULL,
    CONSTRAINT "PK_device_sessions" PRIMARY KEY ("Id")
);

CREATE TABLE oidc_applications (
    "Id" uuid NOT NULL,
    "ApplicationType" character varying(50) NULL,
    "ClientId" character varying(100) NULL,
    "ClientSecret" text NULL,
    "ClientType" character varying(50) NULL,
    "ConcurrencyToken" character varying(50) NULL,
    "ConsentType" character varying(50) NULL,
    "DisplayName" text NULL,
    "DisplayNames" text NULL,
    "JsonWebKeySet" text NULL,
    "Permissions" text NULL,
    "PostLogoutRedirectUris" text NULL,
    "Properties" text NULL,
    "RedirectUris" text NULL,
    "Requirements" text NULL,
    "Settings" text NULL,
    CONSTRAINT "PK_oidc_applications" PRIMARY KEY ("Id")
);

CREATE TABLE oidc_scopes (
    "Id" uuid NOT NULL,
    "ConcurrencyToken" character varying(50) NULL,
    "Description" text NULL,
    "Descriptions" text NULL,
    "DisplayName" text NULL,
    "DisplayNames" text NULL,
    "Name" character varying(200) NULL,
    "Properties" text NULL,
    "Resources" text NULL,
    CONSTRAINT "PK_oidc_scopes" PRIMARY KEY ("Id")
);

CREATE TABLE organizations (
    "Id" uuid NOT NULL,
    "Name" character varying(160) NOT NULL,
    "Slug" character varying(80) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_organizations" PRIMARY KEY ("Id")
);

CREATE TABLE roles (
    "Id" uuid NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY ("Id")
);

CREATE TABLE sync_changes (
    "Checkpoint" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrganizationId" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "EntityType" character varying(80) NOT NULL,
    "ChangedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sync_changes" PRIMARY KEY ("Checkpoint")
);

CREATE TABLE sync_clients (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "DisplayName" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    "Version" bigint NOT NULL,
    "ChangedBy" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sync_clients" PRIMARY KEY ("Id")
);

CREATE TABLE sync_operations (
    "OrganizationId" uuid NOT NULL,
    "OperationId" uuid NOT NULL,
    "EntityId" uuid NOT NULL,
    "Status" character varying(32) NOT NULL,
    "ResultVersion" bigint NOT NULL,
    "AppliedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sync_operations" PRIMARY KEY ("OrganizationId", "OperationId")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "DisplayName" character varying(160) NOT NULL,
    "IsActive" boolean NOT NULL,
    "Version" bigint NOT NULL,
    "LastAccessAtUtc" timestamp with time zone NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE oidc_authorizations (
    "Id" uuid NOT NULL,
    "ApplicationId" uuid NULL,
    "ConcurrencyToken" character varying(50) NULL,
    "CreationDate" timestamp with time zone NULL,
    "Properties" text NULL,
    "Scopes" text NULL,
    "Status" character varying(50) NULL,
    "Subject" character varying(400) NULL,
    "Type" character varying(50) NULL,
    CONSTRAINT "PK_oidc_authorizations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_oidc_authorizations_oidc_applications_ApplicationId" FOREIGN KEY ("ApplicationId")
        REFERENCES oidc_applications ("Id")
);

CREATE TABLE role_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_role_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_role_claims_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE
);

CREATE TABLE user_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_user_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_user_claims_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_logins (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_user_logins_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_roles (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_user_roles_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE user_tokens (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_user_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE oidc_tokens (
    "Id" uuid NOT NULL,
    "ApplicationId" uuid NULL,
    "AuthorizationId" uuid NULL,
    "ConcurrencyToken" character varying(50) NULL,
    "CreationDate" timestamp with time zone NULL,
    "ExpirationDate" timestamp with time zone NULL,
    "Payload" text NULL,
    "Properties" text NULL,
    "RedemptionDate" timestamp with time zone NULL,
    "ReferenceId" character varying(100) NULL,
    "Status" character varying(50) NULL,
    "Subject" character varying(400) NULL,
    "Type" character varying(150) NULL,
    CONSTRAINT "PK_oidc_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_oidc_tokens_oidc_applications_ApplicationId" FOREIGN KEY ("ApplicationId")
        REFERENCES oidc_applications ("Id"),
    CONSTRAINT "FK_oidc_tokens_oidc_authorizations_AuthorizationId" FOREIGN KEY ("AuthorizationId")
        REFERENCES oidc_authorizations ("Id")
);

CREATE INDEX "IX_audit_events_OrganizationId_TimestampUtc" ON audit_events ("OrganizationId", "TimestampUtc");
CREATE INDEX "IX_device_sessions_OrganizationId_UserId_RevokedAtUtc" ON device_sessions ("OrganizationId", "UserId", "RevokedAtUtc");
CREATE UNIQUE INDEX "IX_oidc_applications_ClientId" ON oidc_applications ("ClientId");
CREATE INDEX "IX_oidc_authorizations_ApplicationId_Status_Subject_Type" ON oidc_authorizations ("ApplicationId", "Status", "Subject", "Type");
CREATE UNIQUE INDEX "IX_oidc_scopes_Name" ON oidc_scopes ("Name");
CREATE INDEX "IX_oidc_tokens_ApplicationId_Status_Subject_Type" ON oidc_tokens ("ApplicationId", "Status", "Subject", "Type");
CREATE INDEX "IX_oidc_tokens_AuthorizationId" ON oidc_tokens ("AuthorizationId");
CREATE UNIQUE INDEX "IX_oidc_tokens_ReferenceId" ON oidc_tokens ("ReferenceId");
CREATE UNIQUE INDEX "IX_organizations_Slug" ON organizations ("Slug");
CREATE INDEX "IX_role_claims_RoleId" ON role_claims ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON roles ("NormalizedName");
CREATE INDEX "IX_sync_changes_OrganizationId_Checkpoint" ON sync_changes ("OrganizationId", "Checkpoint");
CREATE INDEX "IX_sync_clients_OrganizationId_DisplayName" ON sync_clients ("OrganizationId", "DisplayName");
CREATE INDEX "IX_sync_clients_OrganizationId_UpdatedAtUtc" ON sync_clients ("OrganizationId", "UpdatedAtUtc");
CREATE INDEX "IX_user_claims_UserId" ON user_claims ("UserId");
CREATE INDEX "IX_user_logins_UserId" ON user_logins ("UserId");
CREATE INDEX "IX_user_roles_RoleId" ON user_roles ("RoleId");
CREATE INDEX "EmailIndex" ON users ("NormalizedEmail");
CREATE INDEX "IX_users_OrganizationId_NormalizedEmail" ON users ("OrganizationId", "NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON users ("NormalizedUserName");

-- AddPhase3ClientCatalog
CREATE TABLE clients (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "PersonType" character varying(32) NOT NULL,
    "LegalNameOrFullName" character varying(200) NOT NULL,
    "PreferredName" character varying(160) NULL,
    "InternalCode" character varying(80) NULL,
    "PrimaryTaxIdNormalized" character varying(14) NOT NULL,
    "IsActive" boolean NOT NULL,
    "DefaultSubjectTemplateId" uuid NULL,
    "DefaultBodyTemplateId" uuid NULL,
    "Notes" character varying(2000) NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedBy" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_clients" PRIMARY KEY ("Id")
);

CREATE TABLE message_templates (
    "Id" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "ClientId" uuid NULL,
    "DocumentTypeId" uuid NULL,
    "Name" character varying(160) NOT NULL,
    "SubjectTemplate" character varying(500) NOT NULL,
    "BodyTemplate" character varying(20000) NOT NULL,
    "SignatureMode" character varying(32) NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "Version" bigint NOT NULL,
    "UpdatedBy" uuid NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_message_templates" PRIMARY KEY ("Id")
);

CREATE TABLE client_establishments (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "CnpjNormalized" character varying(14) NOT NULL,
    "CnpjRoot" character varying(8) NOT NULL,
    "LegalName" character varying(200) NOT NULL,
    "DisplayName" character varying(200) NOT NULL,
    "InternalCode" character varying(80) NULL,
    "IsHeadOffice" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_client_establishments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_client_establishments_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id") ON DELETE RESTRICT
);

CREATE TABLE client_identifiers (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "Type" character varying(32) NOT NULL,
    "ValueNormalized" character varying(200) NOT NULL,
    "SemanticRole" character varying(40) NOT NULL,
    "Priority" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsUniqueWithinOrganization" boolean NOT NULL,
    CONSTRAINT "PK_client_identifiers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_client_identifiers_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id") ON DELETE RESTRICT
);

CREATE TABLE client_recipients (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "EstablishmentId" uuid NULL,
    "DisplayName" character varying(160) NOT NULL,
    "EmailNormalized" character varying(254) NOT NULL,
    "DeliveryRole" character varying(32) NOT NULL,
    "DocumentTypeId" uuid NULL,
    "IsPrimary" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "ValidFrom" date NULL,
    "ValidTo" date NULL,
    CONSTRAINT "PK_client_recipients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_client_recipients_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_client_establishments_ClientId_IsActive" ON client_establishments ("ClientId", "IsActive");
CREATE UNIQUE INDEX "IX_client_establishments_OrganizationId_CnpjNormalized" ON client_establishments ("OrganizationId", "CnpjNormalized");
CREATE INDEX "IX_client_identifiers_ClientId_IsActive_Priority" ON client_identifiers ("ClientId", "IsActive", "Priority");
CREATE UNIQUE INDEX "IX_client_identifiers_OrganizationId_Type_ValueNormalized" ON client_identifiers ("OrganizationId", "Type", "ValueNormalized");
CREATE UNIQUE INDEX "IX_client_recipients_ClientId_EstablishmentId_EmailNormalized_~" ON client_recipients ("ClientId", "EstablishmentId", "EmailNormalized", "DeliveryRole", "DocumentTypeId");
CREATE INDEX "IX_client_recipients_ClientId_IsActive" ON client_recipients ("ClientId", "IsActive");
CREATE UNIQUE INDEX "IX_clients_OrganizationId_InternalCode" ON clients ("OrganizationId", "InternalCode");
CREATE INDEX "IX_clients_OrganizationId_IsActive_LegalNameOrFullName" ON clients ("OrganizationId", "IsActive", "LegalNameOrFullName");
CREATE UNIQUE INDEX "IX_clients_OrganizationId_PrimaryTaxIdNormalized" ON clients ("OrganizationId", "PrimaryTaxIdNormalized");
CREATE UNIQUE INDEX "IX_message_templates_OrganizationId_ClientId_Name" ON message_templates ("OrganizationId", "ClientId", "Name");
CREATE INDEX "IX_message_templates_OrganizationId_IsActive_ClientId" ON message_templates ("OrganizationId", "IsActive", "ClientId");

-- AddPrePhase9ClientPartners (+ AddPartnerOptionalEmail)
CREATE TABLE client_partners (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "CpfNormalized" character varying(11) NULL,
    "Role" character varying(40) NOT NULL,
    "IsActive" boolean NOT NULL,
    "EmailNormalized" character varying(254) NULL,
    CONSTRAINT "PK_client_partners" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_client_partners_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_client_partners_ClientId_IsActive_FullName" ON client_partners ("ClientId", "IsActive", "FullName");
CREATE INDEX "IX_client_partners_OrganizationId_CpfNormalized" ON client_partners ("OrganizationId", "CpfNormalized");

-- AddPhase12ProductionRollout
CREATE TABLE production_dispatch_authorizations (
    "OperationId" uuid NOT NULL,
    "OrganizationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "DeviceId" uuid NOT NULL,
    "ProviderKey" character varying(40) NOT NULL,
    "DispatchFingerprint" character varying(64) NOT NULL,
    "BatchSize" integer NOT NULL,
    "AttachmentCount" integer NOT NULL,
    "ApplicationVersion" character varying(32) NOT NULL,
    "AuthorizationDateUtc" character varying(10) NOT NULL,
    "AuthorizedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_production_dispatch_authorizations" PRIMARY KEY ("OrganizationId", "OperationId")
);
CREATE INDEX "IX_production_dispatch_authorizations_OrganizationId_Authoriza~" ON production_dispatch_authorizations ("OrganizationId", "AuthorizationDateUtc");
CREATE INDEX "IX_production_dispatch_authorizations_OrganizationId_UserId_Au~" ON production_dispatch_authorizations ("OrganizationId", "UserId", "AuthorizationDateUtc");
