// <auto-generated />
using System;
using FolhasDaMichelly.Infrastructure.Persistence.Local;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolhasDaMichelly.Infrastructure.Persistence.Local.Migrations
{
    [DbContext(typeof(LocalCacheDbContext))]
    [Migration("20260821022858_AddPhase5DocumentReview")]
    partial class AddPhase5DocumentReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.CachedClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cached_clients", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.CatalogCacheRecord", b =>
                {
                    b.Property<string>("RecordType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordType", "RecordId");

                    b.HasIndex("RecordType", "UpdatedAtUtc");

                    b.ToTable("catalog_cache", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.DocumentRecognitionCacheRecord", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecognizedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Sha256");

                    b.HasIndex("EngineVersion", "RecognizedAtUtc");

                    b.ToTable("document_recognition_cache", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.DocumentReviewAuditRecord", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScopeKey", "EventId");

                    b.HasIndex("ScopeKey", "DocumentId");

                    b.HasIndex("ScopeKey", "GroupId");

                    b.HasIndex("ScopeKey", "TimestampUtc");

                    b.ToTable("document_review_audit", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.DocumentReviewGroupRecord", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScopeKey", "GroupId");

                    b.HasIndex("ScopeKey", "ClientId", "PeriodKey");

                    b.ToTable("document_review_groups", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.DocumentReviewRecord", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SemanticDuplicateKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScopeKey", "DocumentId");

                    b.HasIndex("ScopeKey", "SemanticDuplicateKey");

                    b.HasIndex("ScopeKey", "Sha256");

                    b.ToTable("document_reviews", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.LocalSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Checkpoint")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.OfflineSyncOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConflicted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextAttemptAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId");

                    b.HasIndex("IsConflicted", "NextAttemptAtUtc");

                    b.ToTable("offline_sync_operations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
