// <auto-generated />
using System;
using FolhasDaMichelly.Infrastructure.Persistence.Local;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolhasDaMichelly.Infrastructure.Persistence.Local.Migrations
{
    [DbContext(typeof(LocalCacheDbContext))]
    [Migration("20260821012514_AddPhase3CatalogCache")]
    partial class AddPhase3CatalogCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.CachedClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("cached_clients", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.CatalogCacheRecord", b =>
                {
                    b.Property<string>("RecordType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecordType", "RecordId");

                    b.HasIndex("RecordType", "UpdatedAtUtc");

                    b.ToTable("catalog_cache", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.LocalSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Checkpoint")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("FolhasDaMichelly.Infrastructure.Persistence.Local.OfflineSyncOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConflicted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextAttemptAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperationId");

                    b.HasIndex("IsConflicted", "NextAttemptAtUtc");

                    b.ToTable("offline_sync_operations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
