[versions]
junit = "5.13.4"
assertj = "3.27.4"
spring-boot = "3.5.6"
jackson = "2.20.0"
flyway = "11.13.1"
postgres = "42.7.8"
sqlite = "3.53.4.0"
testcontainers = "1.21.3"
pdfbox = "3.0.5"
poi = "5.4.1"
openpdf = "2.4.0"
javafx = "25"
jna = "5.18.0"
msal = "1.26.0"
angus-mail = "2.0.5"
nimbus = "10.5"
totp = "1.7.1"
slf4j = "2.0.17"
logback = "1.5.18"
archunit = "1.4.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
sqlite = { module = "io.github.willena:sqlite-jdbc", version.ref = "sqlite" }
testcontainers-pg = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
poi = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
openpdf = { module = "com.github.librepdf:openpdf", version.ref = "openpdf" }
jna = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
msal = { module = "com.microsoft.azure:msal4j", version.ref = "msal" }
angus-mail = { module = "org.eclipse.angus:angus-mail", version.ref = "angus-mail" }
nimbus-jose = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus" }
totp = { module = "dev.samstevens.totp:totp", version.ref = "totp" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
