folhas.environment=Development
folhas.database.migrate-on-startup=true
folhas.authentication.enable-development-scheme=true
folhas.oidc.issuer=http://localhost:8080
folhas.phase10.beta-channel-enabled=true
